# Generated by Django 3.0.4 on 2020-03-10 15:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='study',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
