# Generated by Django 3.0.4 on 2020-03-13 08:55

from django.db import migrations, models
import dt.models
import dt.storages


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(storage=dt.storages.OverwriteStorage(), upload_to=dt.models.get_avatar_path),
        ),
    ]
