# Generated by Django 3.0.4 on 2020-03-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0004_auto_20200313_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='scores',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dt.Book'),
        ),
        migrations.RemoveField(
            model_name='log',
            name='pages',
        ),
        migrations.CreateModel(
            name='PageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dt.Log')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dt.Page')),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='pages',
            field=models.ManyToManyField(through='dt.PageLog', to='dt.Page'),
        ),
    ]
