# Generated by Django 3.0.4 on 2020-03-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0006_auto_20200314_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slogan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
