# Generated by Django 3.0.4 on 2020-03-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dt', '0007_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(default='default.png', upload_to='thumbnail'),
            preserve_default=False,
        ),
    ]
